In [1]:
import numpy as np
import pandas as pd
import math
import random as rd
import collections as clt
import statistics as sts

import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
# Quái vật
monster = 1.0

# Xác suất bắn trúng
p_hit = 0.25

# Mức máu hao hụt khi trúng đạn
reducetion = -0.2

# Số lần mô phỏng
N = 100_000_000

In [121]:
# Đếm số lần bắn cho đến khi quái vật chết
def count_number_shots(monster:float=monster, weight:float=p_hit, amount_reduce:float=reducetion):
    count = 0
    while (monster > 0.0):
        if rd.choices(['Trúng', 'Trượt'], [weight, 1-weight])[0] == 'Trúng':
            monster += amount_reduce
        count += 1
    return count

# Tính xác suất bắn quái vật chết không quá 20 lần bắn
def compute_frequency(num_simulation:np.uint64=N):
    count = 0
    for _ in range(num_simulation):
        if count_number_shots() < 21:
            count += 1
    return float("{:.3f}".format(count/num_simulation))

print(np.mean(np.random.choice(2, size=N, p=[1-.25, .25])))

0.24997785


In [171]:
hits = np.random.choice(2, size=1, p=[.75, .25]) == 1
hits

array([ True])

In [34]:
np.random.choice(['a', 'b', 'c', 'd'], 3)

array(['a', 'd', 'b'], dtype='<U1')

In [39]:
temp = [1, 2, 1, 1, 2, 2, 1, 3, 3, 3, 3]
sts.mode(temp)

1

In [220]:
# Số tiền đặt cược
bet_amount = 1

# Số lần mô phỏng
N = 200_000

# Mô phỏng trò chơi
def is_win(capital:int, target:np.uint64, prob:float, amount:np.uint64=bet_amount) -> bool:
    while 0 < capital and capital < target:
        if np.random.choice(['Thắng', 'Thua'], 1, p=[prob, 1-prob])[0] == 'Thắng':
            capital += amount
        else:
            capital -= amount
    print(capital)
    return True if capital == target else False

In [243]:
is_win(90, 100, 0.5)

0


False

In [133]:
np.random.choice(['Thắng', 'Thua'], 2, True, [0.5, 0.5])

array(['Thua', 'Thua'], dtype='<U5')

$\binom{x}{4}$

In [13]:
test_ = np.arange(1,10,1).reshape((3,3))
print(np.linalg.qr(test_), '\n', test_)

(array([[-0.12309149,  0.90453403,  0.40824829],
       [-0.49236596,  0.30151134, -0.81649658],
       [-0.86164044, -0.30151134,  0.40824829]]), array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
       [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
       [ 0.00000000e+00,  0.00000000e+00, -7.58790979e-16]])) 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
